#!/usr/bin/env bash

APP="publit" # name of your release

BUILD_HOST="acacito.com" # host where to build the release
BUILD_USER="deploy" # local user at build host
BUILD_AT="/tmp/erlang/publit/builds" # build directory on build host
RELEASE_STORE=deploy@acacito.com:/home/deploy/releases

#STAGING_HOSTS="test1.acme.org test2.acme.org" # staging / test hosts separated by space
#STAGING_USER="test" # local user at staging hosts
#TEST_AT="/test/my-erlang-app" # deploy directory on staging hosts. default is DELIVER_TO

PRODUCTION_HOSTS="acacito.com" # deploy / production hosts separated by space
PRODUCTION_USER="deploy" # local user at deploy hosts
DELIVER_TO="/home/deploy/deploys" # deploy directory on production hosts

AUTO_VERSION=git-revision

USING_DISTILLERY=true

pre_erlang_clean_compile() {
  status "Installing NPM dependencies with yarn"
  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e

    cd '$BUILD_AT'
    yarn install $SILENCE
  "

  status "Building static files"
  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e

    cd '$BUILD_AT'
    mkdir -p priv/static
    npm run deploy $SILENCE
  "

  status "Running phoenix.digest"
  __sync_remote "
    [ -f ~/.profile ] && source ~/.profile
    set -e

    cd '$BUILD_AT'
    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
  "
}
